// i18n + mock data
const STRINGS = {
  fr: {
    home: 'Accueil', collect: 'Collecter', impact: 'Impact', wallet: 'Portefeuille', profile: 'Profil',
    greeting: 'Bonjour', greetingMorning: 'Bonjour', greetingAfternoon: 'Bon après-midi', greetingEvening: 'Bonsoir',
    myBin: 'Ma poubelle YECO', syncedNow: 'Synchronisée à l\'instant', syncedAgo: 'Synchronisée',
    organic: 'Organique', nonOrganic: 'Non-organique', recyclable: 'Recyclable',
    fillingUp: 'Se remplit', almostFull: 'Presque pleine', empty: 'Vide', fine: 'Bien',
    requestCollection: 'Demander une collecte', quickActions: 'Accès rapide',
    sortGuide: 'Guide de tri', scanWaste: 'Scanner un déchet', reportIssue: 'Signaler un souci',
    nextCollection: 'Prochaine collecte', tomorrow: 'Demain', morning: 'Matin', afternoon: 'Après-midi', evening: 'Soir',
    todayImpact: 'Votre impact aujourd\'hui', co2Avoided: 'kg CO₂ évités', treesEquivalent: 'arbres',
    ecopoints: 'Écopoints', thisMonth: 'ce mois',
    neighborhoodRank: 'Classement du quartier', yourRank: 'Votre place',
    seeAll: 'Tout voir', continue: 'Continuer', confirm: 'Confirmer',
    pickSlot: 'Choisir un créneau', selectDate: 'Choisir une date',
    today: 'Aujourd\'hui', organicCollection: 'Collecte organique', nonOrgCollection: 'Collecte non-organique',
    freeLabel: 'Gratuit', included: 'Inclus dans abonnement', paymentOption: 'Paiement à l\'acte',
    mtnMomo: 'MTN MoMo', orangeMoney: 'Orange Money', useEcopoints: 'Utiliser des Écopoints',
    collectorOnWay: 'Collecteur en route', collected: 'Collecté', assigned: 'Collecteur assigné', pending: 'En attente', validated: 'Validé',
    arrivesIn: 'Arrive dans', minutes: 'min',
    rating: 'Note', collections: 'collectes',
    weeklyQuest: 'Défi de la semaine', streakDays: 'jours consécutifs',
    earnMore: 'Gagner plus', redeem: 'Utiliser mes points',
    badges: 'Badges', unlock: 'Débloqué',
    plasticRecycled: 'plastique recyclé', sinceJoined: 'depuis votre inscription',
    subscription: 'Abonnement', essential: 'Essentiel', premium: 'Premium', activeUntil: 'Actif jusqu\'au',
    addBin: 'Ajouter une poubelle', scanQR: 'Scanner le QR code',
    back: 'Retour', next: 'Suivant', full: 'Pleine',
    fcfa: 'FCFA',
    live: 'En direct',
    notifTitle: 'Compartiment organique presque plein',
    notifBody: 'Programmez une collecte en 30 secondes',
    congrats: 'Bravo !', badgeEarned: 'Nouveau badge débloqué',
    pionneer: 'Pionnier', ecoHero: 'Éco-Héros', ambassador: 'Ambassadeur',
    kgShort: 'kg', plasticBottles: 'bouteilles', meals: 'repas',
    alertsToday: 'Aujourd\'hui', notifications: 'Notifications',
    binFull: 'Votre poubelle est presque pleine', binFullSub: 'Compartiment organique à 84 %',
    collectionConfirmed: 'Collecte confirmée', collectionConfirmedSub: 'Demain matin • Samuel T.',
    newBadge: 'Nouveau badge !', newBadgeSub: 'Vous avez débloqué Éco-Héros',
    monthly: '/mois', perWeek: '/semaine',
    details: 'Détails', cancel: 'Annuler',
    search: 'Rechercher',
    findBin: 'Où jeter ce déchet ?', plastic: 'Plastique', paper: 'Papier', glass: 'Verre', metal: 'Métal',
    hazard: 'Déchets spéciaux', food: 'Déchets alimentaires',
    slotMorning: '7h–12h', slotAfternoon: '12h–17h', slotEvening: '17h–20h',
    estimateArrival: 'Créneau estimé',
    requestSent: 'Demande envoyée',
    requestSentSub: 'Nous cherchons un collecteur dans votre zone',
    youSaved: 'Vous avez économisé',
    weeksStreak: 'semaines consécutives',
    trackCollection: 'Suivre la collecte',
    viewCollector: 'Voir le collecteur',
    callDriver: 'Appeler', chatDriver: 'Message',
  },
  en: {
    home: 'Home', collect: 'Collect', impact: 'Impact', wallet: 'Wallet', profile: 'Profile',
    greetingMorning: 'Good morning', greetingAfternoon: 'Good afternoon', greetingEvening: 'Good evening',
    myBin: 'My YECO bin', syncedNow: 'Synced just now', syncedAgo: 'Synced',
    organic: 'Organic', nonOrganic: 'Non-organic', recyclable: 'Recyclable',
    fillingUp: 'Filling up', almostFull: 'Almost full', empty: 'Empty', fine: 'Fine',
    requestCollection: 'Request a pickup', quickActions: 'Quick actions',
    sortGuide: 'Sorting guide', scanWaste: 'Scan waste', reportIssue: 'Report issue',
    nextCollection: 'Next pickup', tomorrow: 'Tomorrow', morning: 'Morning', afternoon: 'Afternoon', evening: 'Evening',
    todayImpact: 'Your impact today', co2Avoided: 'kg CO₂ avoided', treesEquivalent: 'trees',
    ecopoints: 'Ecopoints', thisMonth: 'this month',
    neighborhoodRank: 'Neighborhood ranking', yourRank: 'Your rank',
    seeAll: 'See all', continue: 'Continue', confirm: 'Confirm',
    pickSlot: 'Pick a time slot', selectDate: 'Select a date',
    today: 'Today', organicCollection: 'Organic pickup', nonOrgCollection: 'Non-organic pickup',
    freeLabel: 'Free', included: 'Included in plan', paymentOption: 'Pay per pickup',
    mtnMomo: 'MTN MoMo', orangeMoney: 'Orange Money', useEcopoints: 'Use Ecopoints',
    collectorOnWay: 'Collector on the way', collected: 'Collected', assigned: 'Collector assigned', pending: 'Pending', validated: 'Validated',
    arrivesIn: 'Arrives in', minutes: 'min',
    rating: 'Rating', collections: 'pickups',
    weeklyQuest: 'Weekly quest', streakDays: 'day streak',
    earnMore: 'Earn more', redeem: 'Redeem my points',
    badges: 'Badges', unlock: 'Unlocked',
    plasticRecycled: 'plastic recycled', sinceJoined: 'since you joined',
    subscription: 'Subscription', essential: 'Essential', premium: 'Premium', activeUntil: 'Active until',
    addBin: 'Add a bin', scanQR: 'Scan the QR code',
    back: 'Back', next: 'Next', full: 'Full',
    fcfa: 'FCFA',
    live: 'Live',
    notifTitle: 'Organic compartment almost full',
    notifBody: 'Schedule a pickup in 30 seconds',
    congrats: 'Great job!', badgeEarned: 'New badge unlocked',
    pionneer: 'Pioneer', ecoHero: 'Eco-Hero', ambassador: 'Ambassador',
    kgShort: 'kg', plasticBottles: 'bottles', meals: 'meals',
    alertsToday: 'Today', notifications: 'Notifications',
    binFull: 'Your bin is almost full', binFullSub: 'Organic compartment at 84%',
    collectionConfirmed: 'Pickup confirmed', collectionConfirmedSub: 'Tomorrow morning • Samuel T.',
    newBadge: 'New badge!', newBadgeSub: 'You unlocked Eco-Hero',
    monthly: '/month', perWeek: '/week',
    details: 'Details', cancel: 'Cancel',
    search: 'Search',
    findBin: 'Where to throw this?', plastic: 'Plastic', paper: 'Paper', glass: 'Glass', metal: 'Metal',
    hazard: 'Hazardous', food: 'Food waste',
    slotMorning: '7am–12pm', slotAfternoon: '12pm–5pm', slotEvening: '5pm–8pm',
    estimateArrival: 'Estimated slot',
    requestSent: 'Request sent',
    requestSentSub: 'Finding a collector in your area',
    youSaved: 'You saved',
    weeksStreak: 'week streak',
    trackCollection: 'Track pickup',
    viewCollector: 'View collector',
    callDriver: 'Call', chatDriver: 'Message',
  },
};

const makeT = (lang) => (key) => STRINGS[lang]?.[key] ?? STRINGS.en[key] ?? key;

// Mock data
const MOCK = {
  user: { name: 'Adèle', fullName: 'Adèle Mbarga', neighborhood: 'Bastos, Yaoundé' },
  bin: { organic: 64, nonOrganic: 32, lastSync: '2 min' },
  ecopoints: 1284,
  monthPoints: 340,
  streak: 21,
  co2Month: 18.4,
  trees: 1.2,
  plasticKg: 6.3,
  rank: 4,
  totalHomes: 86,
  leaderboard: [
    { name: 'Famille Njoya', pts: 1842, rank: 1, color: '#f4a261' },
    { name: 'Famille Tchoungui', pts: 1605, rank: 2, color: '#2a9d8f' },
    { name: 'Famille Ekani', pts: 1390, rank: 3, color: '#e76f51' },
    { name: 'Vous', pts: 1284, rank: 4, color: 'var(--leaf)', you: true },
    { name: 'Famille Bissou', pts: 1201, rank: 5, color: '#8ecae6' },
  ],
  collector: { name: 'Samuel T.', rating: 4.8, collections: 312, eta: 14 },
};

Object.assign(window, { STRINGS, makeT, MOCK });
